# Generated by Django 4.2.7 on 2023-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100)),
                ('page_header', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('help_to', models.CharField(max_length=100)),
                ('help_to_content', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='home_profile')),
                ('about_me_header', models.CharField(max_length=200)),
                ('about_me_content', models.CharField(max_length=500)),
                ('instagram_link', models.CharField(max_length=200)),
                ('linkedin_link', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'HomeData',
            },
        ),
    ]
