# Generated by Django 4.2.7 on 2024-01-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='تاریخ')),
                ('time', models.CharField(max_length=20, verbose_name='زمان')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('agent', models.CharField(max_length=500, verbose_name='مرورگر')),
                ('language', models.CharField(max_length=100, verbose_name='زبان')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدید ها',
            },
        ),
    ]
