# Generated by Django 4.2.7 on 2024-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_alter_logger_options_alter_logger_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
