# Generated by Django 4.2.7 on 2024-01-23 12:47

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('datetime', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
