# Generated by Django 4.2.7 on 2023-11-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
