# Generated by Django 4.2.7 on 2023-11-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_language_resumeexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeExperience',
            new_name='Experience',
        ),
    ]
