# Generated by Django 4.2.7 on 2023-11-18 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_rename_resumeexperience_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='priority',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
