# Generated by Django 4.2.7 on 2024-01-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_experience_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('is_present', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'Education',
            },
        ),
    ]
