# Generated by Django 4.2.7 on 2024-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
