# Generated by Django 4.2.7 on 2024-01-17 07:17

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_education_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='ResumeFiles/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume File',
                'verbose_name_plural': 'Resume Files',
                'db_table': 'ResumeFile',
            },
        ),
    ]
