# Generated by Django 4.2.7 on 2024-01-22 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_resumefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
